"""test autorevision

Revision ID: 83cef207ee26
Revises: b0ce765ed960
Create Date: 2017-05-17 16:09:40.424225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83cef207ee26'
down_revision = 'b0ce765ed960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
