"""test autorevision

Revision ID: b0ce765ed960
Revises: 91432d54dbbb
Create Date: 2017-05-17 15:59:26.281070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0ce765ed960'
down_revision = '91432d54dbbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
